name: Pillars
version: 2.0.0

main: TheWindows\Pillars\Main
api: 5.0.0
authors: [TheWindows, Doma]

description: Pillars of Fortune minigame for PocketMine-MP

virions:
  - apibossbar
  - libFormAPI

permissions:
  pillars.admin:
    description: "Allows access to Pillars admin commands"
    default: op
  pillars.join:
    description: "Allows players to join Pillars games"
    default: true
